# Generated by Django 5.2.8 on 2025-11-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('project_type', models.CharField(choices=[('Mobile App', 'Mobile App'), ('Web Platform', 'Web Platform'), ('AI Integration', 'AI Integration'), ('Digital Marketing', 'Digital Marketing'), ('Retail System', 'Retail System')], max_length=50)),
                ('budget', models.CharField(choices=[('$1k - $5k', '$1k - $5k'), ('$5k - $10k', '$5k - $10k'), ('$10k - $50k', '$10k - $50k'), ('$50k+', '$50k+')], max_length=50)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('mobile', 'Mobile Apps'), ('web', 'Web Platforms'), ('ai', 'AI & Data')], max_length=20)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(help_text='e.g. React, Django, AWS', max_length=200)),
                ('image', models.ImageField(upload_to='projects/')),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
